Updated Docs For Java
Brown-County-FIRST-Robotics/1716-2024-robot pull request #18
Opened 2024-01-19 20:38 UTC by gldeA

I updated some of the docs files from last year, editing them and converting C++ to Java.

2024-01-19 23:51 UTC, cfinn68916 requested changes
See comments

2024-01-19 23:51 UTC, cfinn68916 commented on docs/command_based.md
> +    () -> { return controller.getLeftY(); }));
Or just pass in the whole XboxController object

2024-01-20 00:18 UTC, gldeA commented on docs/command_based.md
> +    () -> { return controller.getLeftY(); }));
Huh, I did not know about the :: operator in Java...

2024-01-20 00:20 UTC, gldeA commented on docs/wpilib_reference.md
> +|`TalonSRX`|`com.ctre.phoenix6.hardware.TalonSRX`|This is probably right, unconfirmed|
Ok... What's the correct path then?

2024-01-20 00:21 UTC, gldeA commented on docs/wpilib_reference.md
> +|`TalonSRX`|`com.ctre.phoenix6.hardware.TalonSRX`|This is probably right, unconfirmed|
`com.ctre.phoenix5.hardware.TalonSRX`?

2024-01-20 00:26 UTC, gldeA commented on docs/can_ids.md
> +|Back Left Motor|2|
This is a mess

2024-01-20 00:29 UTC, gldeA commented on docs/can_ids.md
> +|Back Left Motor|2|
Also, 10 and 20 were conflicting, so I changed them to 18 and 19

2024-01-20 00:47 UTC, gldeA commented
Should be fixed

2024-01-20 01:42 UTC, cfinn68916 approved these changes
LGTM (let's gamble try merging). I still prefer passing the controller object reference into commands instead of lambdas.

2024-01-20 01:46 UTC, gldeA commented
> I still prefer passing the controller object reference into commands instead of lambdas.
I disagree, best practice is generally to provide only as much access as you need, and passing the full controller in is unnecessary (though it could be a good idea when you need a lot of controller inputs in one command rather than just one or two)

2024-01-20 01:46 UTC, merged